<?php

use Drupal\views\Plugin\views\cache\CachePluginBase;
use Drupal\views\ViewExecutable;

function idc_ui_module_theme($existing, $type, $theme, $path) {
  return [
    'header_left_template' => [
      'variables' => ['test_var' => NULL],
    ],
    'top_nav_template' => [
      'variables' => ['logged_in' => NULL],
    ],
    'footer_template' => [
      'variables' => [],
    ],
    'page--collections' => [
      'variables' => [
        'featured_collections' => NULL,
      ],
    ],
    'page--collection' => [
      'variables' => [
        'collection' => NULL,
        'featured_items' => NULL,
        'primary_description' => NULL,
        'citable_url' => NULL,
      ],
    ],
    'page--item' => [
      'variables' => [
        'item' => NULL,
      ],
    ],
    'page--search' => [
      'variables' => []
    ],
    'idc_search_template' => [
      'variables' => []
    ],
    'page--advanced-search' => [
      'variables' => []
    ]
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function idc_ui_module_form_views_exposed_form_alter(&$form, $form_state) {
  // XXX: Exposed filters with REST appear to still render a form even though
  // it technically does not use one.
  if ($form['#action'] === "/search_rest_endpoint") {
    // Set the limit to be close to the lower bound URL parameter limit.
    $form['query']['#maxlength'] = 65536;
  }
}

/**
 * Implements hook_views_post_render().
 */
function idc_ui_module_views_post_render(ViewExecutable $view, &$output, CachePluginBase $cache) {
  // XXX: Cache max-age 0 isn't able to be utlized by anonymous users.
  // Similarly, a Serializer's cacheable metadata does not get bubbled up to the
  // view and thus we are stuck with setting our own cache tags. In the event
  // indexing more than just content (nodes) gets done this should be updated
  // to include those tags as well.
  // @see: https://www.drupal.org/docs/drupal-apis/cache-api/cache-max-age
  // @see: https://www.drupal.org/project/drupal/issues/3210146
  // @see: https://www.drupal.org/project/facets/issues/2939710
  if ($view->id() === 'solr_search_content') {
    $output['#cache']['tags'][] = 'node_list';
  }
}
