<?php

function idc_ui_module_theme($existing, $type, $theme, $path) {
  return [
    'header_left_template' => [
      'variables' => ['test_var' => NULL],
    ],
    'top_nav_template' => [
      'variables' => ['logged_in' => NULL],
    ],
    'footer_template' => [
      'variables' => [],
    ],
    'page--collections' => [
      'variables' => [
        'featured_collections' => NULL,
      ],
    ],
    'page--collection' => [
      'variables' => [
        'collection' => NULL,
        'featured_items' => NULL,
      ],
    ],
    'page--item' => [
      'variables' => [
        'item' => NULL,
      ],
    ],
  ];
}
